# Generated by Django 5.2.1 on 2025-05-20 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_onetimepassword_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='account.userprofile')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_by_referrer', to='account.userprofile')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-referred_at'],
                'indexes': [models.Index(fields=['code'], name='management__code_595921_idx'), models.Index(fields=['referee'], name='management__referee_39988c_idx'), models.Index(fields=['referrer'], name='management__referre_b4be09_idx')],
                'constraints': [models.UniqueConstraint(fields=('referee',), name='unique_referral_per_user')],
            },
        ),
    ]
