# Generated by Django 5.2.1 on 2025-05-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='management__name_bfee2d_idx'), models.Index(fields=['email'], name='management__email_d078e3_idx'), models.Index(fields=['created_at'], name='management__created_8e4d2f_idx')],
            },
        ),
    ]
